apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort  # Use LoadBalancer in cloud
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
